title: Proyecto segundo parcial de Introduccion a la inguieneria en software
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alfredo Czarninski # add your name
author-img: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vistazo.com%2Fseccion%2Fgente%2Funa-historia-de-vision-y-perseverancia&psig=AOvVaw3wmv0rY4Be-gaysXzliFqp&ust=1602110749779000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNCFy-SFoewCFQAAAAAdAAAAABAD
about-author: Fue un comerciante y filántropo israelí, creador del Grupo El Rosado y Mi Comisariato. # add description
social-twitter: @mi_comisariato # add your Twitter handle
social-facebook: micomisariatoec # add your Facebook handle
social-email: servicioalcliente@elrosado.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
